config/routes.rb
Rails.application.routes.draw do
  
  resources :devices do
    collection do
      get :pos_payment
    end
  end
  
  resources :attachments do
    member do
      get :download
    end
  end
  resources :commodity_items
  resources :transactions
  resources :customers
  resources :users
  
  resources :companies
  
  resources :commodities
  
  resources :sessions
  
  get 'welcome/index'
  root 'welcome#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup' => 'companies#new'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  
  mount_uploader :file, FileUploader

  # Associations
  belongs_to :attached_item, polymorphic: true
  
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy, :download]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to edit_transaction_path(@attachment.attached_item), notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def download
    send_file @attachment.file.path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:name, :description, :file, :attached_item_id, :attached_item_type, :original_filename, :content_type)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.haml
= form_for @attachment do |f|
  - if @attachment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@attachment.errors.count, "error")} prohibited this attachment from being saved:"
      %ul
        - @attachment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :file
    =# f.text_field :file
    = f.file_field :file
  .field
    = f.label :attached_item_id
    = f.number_field :attached_item_id
  .field
    = f.label :attached_item_type
    = f.text_field :attached_item_type
  .field
    = f.label :original_filename
    = f.text_field :original_filename
  .field
    = f.label :content_type
    = f.text_field :content_type
  .actions
    = f.submit 'Save'

app/views/attachments/edit.html.haml
%h1 Editing attachment

= render 'form'

= link_to 'Show', @attachment
\|
= link_to 'Back', attachments_path

app/views/attachments/index.html.haml
%h1 Listing attachments

%table
  %thead
    %tr
      %th Name
      %th Description
      %th File
      %th Attached item
      %th Attached item type
      %th Original filename
      %th Content type
      %th
      %th
      %th

  %tbody
    - @attachments.each do |attachment|
      %tr
        %td= attachment.name
        %td= attachment.description
        %td= attachment.file
        %td= attachment.attached_item_id
        %td= attachment.attached_item_type
        %td= attachment.original_filename
        %td= attachment.content_type
        %td= link_to 'Show', attachment
        %td= link_to 'Edit', edit_attachment_path(attachment)
        %td= link_to 'Destroy', attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Attachment', new_attachment_path

app/views/attachments/new.html.haml
%h1 New attachment

= render 'form'

= link_to 'Back', attachments_path

app/views/attachments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @attachment.name
%p
  %b Description:
  = @attachment.description
%p
  %b File:
  = @attachment.file
%p
  %b Attached item:
  = @attachment.attached_item_id
%p
  %b Attached item type:
  = @attachment.attached_item_type
%p
  %b Original filename:
  = @attachment.original_filename
%p
  %b Content type:
  = @attachment.content_type

= link_to 'Edit', edit_attachment_path(@attachment)
\|
= link_to 'Back', attachments_path