config/routes.rb
Rails.application.routes.draw do
  
  resources :devices do
    collection do
      get :pos_payment
    end
  end
  
  resources :attachments do
    member do
      get :download
    end
  end
  resources :commodity_items
  resources :transactions
  resources :customers
  resources :users
  
  resources :companies
  
  resources :commodities
  
  resources :sessions
  
  get 'welcome/index'
  root 'welcome#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup' => 'companies#new'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :login_required
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { 
          redirect_to @transaction, notice: 'Transaction was successfully updated.' unless @transaction.status == 'Incomplete'
          redirect_to edit_transaction_path(@transaction), notice: 'Transaction was successfully updated.' if @transaction.status == 'Incomplete'
          }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:customer_id, :user_id, :category, :status, :discount, :tax, :total, :ez_cash_tran_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_attachment_modal.html.haml
#attachment.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "attachment_label", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body
        = form_for Attachment.new do |form|
          = form.hidden_field :attached_item_id, value: @transaction.id
          = form.hidden_field :attached_item_type, value: @transaction.class.name
          .form-group.row
            .col-sm-12
              = form.text_field :name, class: 'form-control form-control-lg', placeholder: 'Name', autofocus: true
          .form-group.row
            .col-sm-12
              = form.text_area :description, class: 'form-control form-control-lg', placeholder: 'Description'
          .form-group.row
            .col-sm-12
              = form.file_field :file
          - unless @transaction.attachments.blank?
            %p.lead Attachments
            %div.card
              %ul.list-group.list-group-flush
                - @transaction.attachments.each do |attachment|
                  %li.list-group-item 
                    = attachment.name
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
            %button.btn.btn-primary{:type => "submit"} Save

app/views/transactions/_commodity_item_modal.html.haml
#add_commodity_item.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "add_commodity_item_label", :role => "dialog"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      -#
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#add_commodity_item_label.modal-title New Commodity Item
      .modal-body
        = form_for(CommodityItem.new) do |form|
          = form.hidden_field :transaction_id, value: @transaction.id
          .form-group.row
            .col-sm-12
              = form.select :commodity_id, options_from_collection_for_select(current_company.commodities, :id, :name), {prompt: "Select commodity"}, {autofocus: true, style: 'width: 100%', :class => "form-control form-control-lg"}
          -#
            .form-group.row
              .col-sm-12
                = form.text_field :total, class: 'form-control form-control-lg', placeholder: 'Total', required: true
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
            %button.btn.btn-primary{:type => "submit"} Save

app/views/transactions/_customer_modal.html.haml
#change_customer.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "change_customer_label", :role => "dialog"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      -#
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#change_customer_label.modal-title Customer
      .modal-body
        = form_for(@transaction) do |form|
          .form-group
            = form.select :customer_id, options_from_collection_for_select(current_company.customers, :id, :full_name, @transaction.customer_id), {prompt: "Select customer"}, {autofocus: true, style: 'width: 100%', :class => "form-control form-control-lg"}
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
            %button.btn.btn-primary{:type => "submit"} Save

app/views/transactions/_discount_modal.html.haml
#change_discount.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "change_discount_label", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      -#
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#change_discount_label.modal-title Discount
      .modal-body
        = form_for(@transaction) do |form|
          .form-group.row
            .col-sm-12
              .input-group
                .input-group-addon 
                  %i.fa.fa-dollar
                = form.text_field :discount, class: 'form-control form-control-lg', placeholder: 'Discount', autofocus: true
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
            %button.btn.btn-primary{:type => "submit"} Save

app/views/transactions/_form.html.haml
%br
= form_for @transaction do |f|
  - if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :ez_cash_tran_id
  .form-group.row
    -#
      %label.required.col-sm-2.form-control-label{:for => "customer"} Customer
    .col-sm-6
      = f.select :customer_id, options_from_collection_for_select(current_company.customers, :id, :full_name), {prompt: "Select customer"}, {:class => "form-control form-control-lg"}
  .form-group.row
    .col-sm-6
      .radio-inline
        %label.required.col-sm-2.form-control-label
          = f.radio_button :category, 'Purchase', required: true
          Buy
      .radio-inline
        %label.required.col-sm-2.form-control-label
          = f.radio_button :category, 'Sale'
          Sell
    .col-sm-6
      .radio-inline
        %label.required.col-sm-2.form-control-label
          = f.radio_button :status, 'Complete', required: true
          Complete
      .radio-inline
        %label.required.col-sm-2.form-control-label
          = f.radio_button :status, 'Incomplete'
          Incomplete
  .form-group.row
    .col-sm-3
      = f.text_field :discount, class: 'form-control', placeholder: 'Discount'
  .form-group.row
    .col-sm-3
      = f.text_field :tax, class: 'form-control', placeholder: 'Tax'
  .form-group.row
    .col-sm-3
      = f.text_field :total, class: 'form-control', placeholder: 'Total'
  .form-group.row
    .col-sm-3
      %button.btn.btn-primary.btn-lg{:type => "submit"} Save

app/views/transactions/_new_transaction_modal.html.haml
#new_transaction.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "new_transaction_label", :role => "dialog"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      .modal-body
        = form_for Transaction.new do |form|
          = form.hidden_field :user_id, value: current_user.id
          = form.hidden_field :category, value: 'Sale'
          = form.hidden_field :status, value: 'Incomplete'
          .form-group.row
            .col-sm-12
              = form.select :customer_id, options_from_collection_for_select(current_company.customers, :id, :full_name), {prompt: "Select customer"}, {autofocus: true, style: 'width: 100%', :class => "form-control form-control-lg"}
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
            %button.btn.btn-primary{:type => "submit"} Go

app/views/transactions/_tax_modal.html.haml
#change_tax.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "change_tax_label", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      -#
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#change_tax_label.modal-title Tax
      .modal-body
        = form_for(@transaction) do |form|
          .form-group.row
            .col-sm-12
              .input-group
                = form.text_field :tax, class: 'form-control form-control-lg', placeholder: 'Tax'
                .input-group-addon 
                  %i.fa.fa-percent
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Cancel
            %button.btn.btn-primary{:type => "submit"} Save

app/views/transactions/edit.html.haml
%br

- unless @transaction.commodity_items.blank?
  %div.card
    %ul.list-group.list-group-flush#commodity_items
      -# Expands to render commodity_items/commodity_item, collection: @transaction.commodity_items
      = render @transaction.commodity_items
- else
  %p.lead No items yet
   
%div.row
  .col-xs-12.col-md-4
    %div.row
      .col-xs-6
        %a.btn.btn-warning-outline.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#add_commodity_item", :role => "button"} 
          %br
          Add
          %br
          %br
      .col-xs-6
        %a.btn.btn-success-outline.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#change_customer", :role => "button"}
          %br
          Customer
          %br
          %br
    %br
    %div.row
      .col-xs-6
        %a.btn.btn-primary-outline.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#change_discount", :role => "button"} 
          %br
          Discount
          %br
          %br
      .col-xs-6
        %a.btn.btn-secondary-outline.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#attachment", :role => "button"}
          %br
          Attachment
          %br
          %br
        -#
          %a.btn.btn-info-outline.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#change_tax", :role => "button"} 
            %br
            Tax
            %br
            %br
    -#
      %br
      %div.row
        .col-xs-6
          %a.btn.btn-secondary-outline.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#attachment", :role => "button"}
            %br
            Attachment
            %br
            %br
    %br
  .col-xs-12.col-md-4
    .card
      %ul.list-group.list-group-flush
        %li.list-group-item
          Customer
          .pull-right= @transaction.customer.full_name
        %li.list-group-item
          Subtotal
          .pull-right= number_to_currency(@transaction.sub_total)
        %li.list-group-item
          Discount
          .pull-right= number_to_currency("#{@transaction.discount.blank? ? 0 : @transaction.discount}")
        %li.list-group-item
          = "Tax #{@transaction.tax.blank? ? '' : '(' + number_to_percentage(@transaction.tax, precision: 2) + ')'}"
          .pull-right= number_to_currency(@transaction.tax_amount)
        %li.list-group-item
          %strong
            Total
            .pull-right= number_to_currency(@transaction.sub_total - @transaction.discount - @transaction.tax_amount)
  .col-xs-12.col-md-4
    - unless @transaction.sub_total.blank? or @transaction.sub_total.zero?
      -#
        %div.row
          .col-xs-12
            %a.btn.btn-warning.btn-lg.btn-block{href: '#'}
              %br
              Check ATM
              %br
              %br
      %br
      %div.row
        .col-xs-12
          = form_for(@transaction, remote: true) do |form|
            = form.hidden_field :status, value: 'Complete'
            = form.hidden_field :ez_cash_tran_id
            -# %button.btn.btn-primary.btn-lg.btn-block{:type => "submit"}
            %a.btn.btn-primary.btn-lg.btn-block{href: nil, id: 'hypercom_charge_button', "data-workstation-id" => 2,  "data-amount" => (@transaction.sub_total - @transaction.discount - @transaction.tax_amount).round(2)}
              %br
              %br
              %i.fa.fa-spinner.fa-lg.fa-spin{style: 'display:none;'}
              Charge
              = number_to_currency(@transaction.sub_total - @transaction.discount - @transaction.tax_amount)
              %br
              %br
              %br
    -#
      .card.card-inverse.card-success.text-xs-center
        .card-block
          %blockquote.card-blockquote
            %br
            %p 
              Charge
              = number_to_currency(@transaction.sub_total - @transaction.discount - @transaction.tax.to_d)

        %br
        -#
          %footer
            Customer:
            = @transaction.customer.full_name

= render 'commodity_item_modal'
= render 'customer_modal'
= render 'discount_modal'
=# render 'tax_modal'
= render 'attachment_modal'

-#
  = render 'form'

  = link_to 'Show', @transaction
  \|
  = link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%br
- unless @transactions.blank?
  %table.table
    %thead
      %tr
        %th Customer
        %th User
        %th Category
        %th Status
        %th Discount
        %th Tax
        %th Total
        %th
        %th
        %th

    %tbody
      - @transactions.each do |transaction|
        %tr
          %td= transaction.customer.full_name
          %td= transaction.user.full_name
          %td= transaction.category
          %td= transaction.status
          %td= number_to_currency(transaction.discount)
          %td= number_to_currency(transaction.tax_amount)
          %td= number_to_currency(transaction.total)
          %td= link_to 'Show', transaction
          %td= link_to 'Edit', edit_transaction_path(transaction)
          %td= link_to 'Destroy', transaction, :method => :delete, :data => { :confirm => 'Are you sure?' }
- else
  %p.lead No transactions

%br
= render 'new_transaction_modal'
%a{:href => "#", "data-toggle" => "modal", "data-target" => "#new_transaction", :role => "button"} New Transaction
=# link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%br
= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%br

%div.row
  .col-xs-4
    %a.btn.btn-warning.btn-lg.btn-block{:href => "#", "data-toggle" => "modal", "data-target" => "#add_commodity_item", :role => "button"} Receipt
  .col-xs-4
    = form_for(@transaction, remote: true) do |form|
      = form.hidden_field :status, value: 'Void'
      %button.btn.btn-danger.btn-lg.btn-block{:type => "submit"}
        Void
  .col-xs-4
    %a.btn.btn-primary.btn-lg.btn-block{href: edit_transaction_path(@transaction), :role => "button"} Edit

%br

%p.lead Details
%div.card-group
  %div.card
    %ul.list-group.list-group-flush
      %li.list-group-item
        Number
        .pull-right= @transaction.id
      %li.list-group-item
        Date
        .pull-right= @transaction.updated_at.strftime("%m/%d/%y, %l:%M %p")
      %li.list-group-item
        Status
        .pull-right= @transaction.status
      %li.list-group-item
        Customer
        .pull-right= link_to @transaction.customer.full_name, @transaction.customer
  %div.card
    %ul.list-group.list-group-flush
      %li.list-group-item
        Subtotal
        .pull-right= number_to_currency(@transaction.sub_total)
      %li.list-group-item
        Discount
        .pull-right= number_to_currency("#{@transaction.discount.blank? ? 0 : @transaction.discount}")
      %li.list-group-item
        = "Tax #{@transaction.tax.blank? ? '' : '(' + number_to_percentage(@transaction.tax, precision: 2) + ')'}"
        .pull-right= number_to_currency(@transaction.tax_amount)
      %li.list-group-item
        %strong Total
        .pull-right
          %strong= number_to_currency("#{@transaction.total.blank? ? 0 : @transaction.total}")
%br
%p.lead Items
- unless @transaction.commodity_items.blank?
  %div.card
    %ul.list-group.list-group-flush
      - @transaction.commodity_items.each do |commodity_item|
        %li.list-group-item 
          = commodity_item.commodity.name
          .pull-right
            = number_to_currency(commodity_item.commodity.price)
          %br
          %small
            .text-muted= commodity_item.commodity.unit_of_measure
- else
  %p.lead No commodity items

%br
%p.lead Attachments
- unless @transaction.attachments.blank?
  %div.card
    %ul.list-group.list-group-flush
      - @transaction.attachments.each do |attachment|
        %li.list-group-item 
          = attachment.name
          .pull-right
            = link_to 'Download', download_attachment_path(attachment)
- else
  %p.lead No attachments
   
-#
  .col-xs-12
    = link_to 'Edit', edit_transaction_path(@transaction)
    \|
    = link_to 'Back', transactions_path